### ISSUE TITLE
[BUG] DEFAULT_SITE_THEME is not editable 

### ISSUE THREAD

**Issue by andrey-canon** [eduNEXT/tutor-contrib-edunext-distro#25]
**Describe the bug**
`DEFAULT_SITE_THEME` can not be modified, the default value is bragi but this is not helpful when the theme is different from `ednx-saas-themes`

**To Reproduce**
Steps to reproduce the behavior with stack-builder:
1. Use this strain https://github.com/eduNEXT/ednx-strains/blob/master/mango/strain.yml
2. Modify the `DISTRO_THEMES_NAME` section, remove bragi* and add a different theme name
3. Make `stack strain dev configure`
4. Open file /env/apps/openedx/config/lms.env.json
5. Check `DEFAULT_SITE_THEME`

**Expected behavior**
`DEFAULT_SITE_THEME` with the first value of `DISTRO_THEMES_NAME` or a setting like `DISTRO_DEFAULT_SITE_THEME` that allows to override the bragi value

**Comment by johanv26** [comment]
https://github.com/eduNEXT/tutor-contrib-edunext-distro/blame/ca91fa4f0699ff01bc46af383a123c3cd5130a80/tutordistro/patches/lms-env#L2

**Comment by MaferMazu** [comment]
The PR #36 add this feature. Thanks @andrey-canon
