### ISSUE TITLE
[BUG] CSV files cannot be uploaded when using s3 as a storage engine

### ISSUE THREAD

**Issue by DonatoBD** [eduNEXT/tutor-contrib-edunext-distro#29]
**Describe the bug**

When we use s3 as a storage engine and try to upload a CSV file, an error occurs where it won't let us upload it to s3. This error was identified using the Staff Graded Points component when uploading a CSV file to modify the grades of the students in the course. 

After some research, it seems that since maple release, this problem occurs and the solution was done in this [PR](https://github.com/openedx/super-csv/pull/100) 

Since the openedx versions do not have this change yet, it would be necessary to update the super-csv package on our side while openedx is updating these requirements

**To Reproduce**
1. Install the minio plugin to be able to simulate locally the connection to s3
2. Create a course
3. Go to Studio > Settings > Advanced settings
4. Add "edx_sga" to the Advanced Module List
5. Go to the course outline, create a unit
6. Add Staff graded points component (Add new component > Problem > Advanced > Staff Graded Points)
7. Publish your unit and check the preview
8. Click on the Export button, open the file, put 1 on the New Points column and click on Import Scores to upload the new file

**Expected behavior**
The csv is processed correctly and a message is displayed saying that the scores were modified

**Screenshots**

**Additional context**

**Comment by santiagosuarezedunext** [comment]
Hi Donato, I am going to follow this PR so you have an answer about it.
I have a question. How Studio users upload csv files today if this is not working?

**Comment by DonatoBD** [comment]
Hi @santiagosuarezedunex, currently users can upload the files because we install that version of the package manually from [strain](https://github.com/eduNEXT/ednx-strains/blob/master/mango/ukgov/strain.yml#L260) when building the image

**Comment by santiagosuarezedunext** [comment]
Este problema es parte del mantenimiento de nuestro producto, tenemos que corregir este error. Voy a moverlo a en progreso. Puedes seguir el progreso [aquí](https://edunext.atlassian.net/browse/DS-482?atlOrigin=eyJpIjoiMTkzZTJlMGU1YmMxNGRiOWE0OGI4NzNmZTlhYWZhNmYiLCJwIjoiaiJ9).

**Comment by dcoa** [comment]
Understanding that super-csv is already updated in olive and the upstream edx-platform, we could close this issue. 
https://github.com/eduNEXT/edunext-platform/blob/ednx-release/olmo.master/requirements/edx/base.txt#L1092 

Add a screenshot for olmo cluster testing:

![image](https://user-images.githubusercontent.com/66016493/232424488-855f1bea-87c6-48b3-b7f1-58f90e2dd941.png)

Thank @DonatoBD for your explanation.

C.C @MaferMazu
