### ISSUE TITLE
[BUG] Wrong CMS development settings

### ISSUE THREAD

**Issue by andrey-canon** [eduNEXT/tutor-contrib-edunext-distro#35]
**Describe the bug**
cms  settings have a wrong value

since distro use this patch https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/master/tutordistro/patches/openedx-development-settings the cms settings are populated with the line `derive_settings("lms.envs.devstack") `when the EOX_THEMING_DEFAULT_THEME_NAME is defined, obviously that is a wrong value in the cms context  that should be `cms.envs.devstack`  or that block shouln't be include in the cms settings, probably that block should be in this file https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/master/tutordistro/patches/openedx-lms-development-settings

**Expected behavior**
cms works normally 

**Screenshots**
![image](https://user-images.githubusercontent.com/36200299/199615427-5f931d1e-e164-41ac-a6c2-dfe628235043.png)

**Comment by MaferMazu** [comment]
We just created this bug in our backlog for review in the next sprints. Thanks for the patience @andrey-canon

**Comment by MaferMazu** [comment]
Friendly reminder of this @Alec4r @andrey-canon
