### ISSUE TITLE
[BUG] Improve doc about theming

### ISSUE THREAD

**Issue by MaferMazu** [eduNEXT/tutor-contrib-edunext-distro#53]
**Describe the bug**
When I set my theming config, I didn't know that I needed `DISTRO_THEMES_ROOT`, and the command tutor distro enable-themes failed if I didn't define it. Please add this to the doc.

**To Reproduce**
Follow the theming instructions in the readme; you can't enable-themes command.

**Expected behavior**
Have the right documentation about how to have theming (We also need to add that we need to install eox-theming)

**Screenshots**
![image](https://github.com/eduNEXT/tutor-contrib-edunext-distro/assets/35668326/901f099a-3d15-4965-98cf-dc4dddd77b08)

**Comment by bra-i-am** [comment]
Hello @MaferMazu, thank you so much for reporting this issue :D
I agree with you that the documentation needs improvement; I am going to create an issue in our backlog to keep it near and work on it in the following sprints.
